In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
a=pd.read_csv(r"Churn_Modelling_with_nulls.csv")

In [4]:
a.shape

(10000, 14)

In [5]:
a.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602.0,Hargrave,619.0,France,Female,NaN,2.0,0.00,1.0,1.0,1.0,101348.88,1.0
1,2,15647311.0,Hill,608.0,Spain,Female,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58,0.0
2,3,15619304.0,Onio,502.0,France,Female,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57,1.0
3,4,15701354.0,Boni,699.0,France,Female,39.0,1.0,0.00,2.0,0.0,0.0,93826.63,0.0
4,5,15737888.0,Mitchell,850.0,Spain,Female,43.0,NaN,125510.82,1.0,1.0,1.0,79084.10,0.0

In [6]:
b=a.isnull().sum()/a.shape[0]*100

In [7]:
b

RowNumber          0.00
CustomerId         4.95
Surname            5.33
CreditScore        5.16
Geography          5.02
Gender             4.81
Age                5.19
Tenure             5.14
Balance            4.97
NumOfProducts      4.86
HasCrCard          4.97
IsActiveMember     4.97
EstimatedSalary    4.81
Exited             4.78
dtype: float64

In [8]:
mask=b>20
mask

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [9]:
c=b[mask].index
c

Index([], dtype='str')

In [10]:
a=a.drop( columns=c)## removing columns
a.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602.0,Hargrave,619.0,France,Female,NaN,2.0,0.00,1.0,1.0,1.0,101348.88,1.0
1,2,15647311.0,Hill,608.0,Spain,Female,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58,0.0
2,3,15619304.0,Onio,502.0,France,Female,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57,1.0
3,4,15701354.0,Boni,699.0,France,Female,39.0,1.0,0.00,2.0,0.0,0.0,93826.63,0.0
4,5,15737888.0,Mitchell,850.0,Spain,Female,43.0,NaN,125510.82,1.0,1.0,1.0,79084.10,0.0

In [11]:
for i in a.select_dtypes(include=['int','float']):
    a[i]=a[i].replace(np.nan,a[i].median())

In [12]:
for i in a.select_dtypes(include=['object']):
    a[i]=a[i].replace(np.nan,a[i].mode()[0])

C:\Users\rahul\AppData\Local\Temp\ipykernel_23020\2275689403.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for i in a.select_dtypes(include=['object']):

In [13]:
a.isnull().sum().sum()

np.int64(0)

## encoding

In [14]:
a.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='str')

In [15]:
a=a.drop(columns='Surname')

In [16]:
a.head()

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602.0,619.0,France,Female,37.0,2.0,0.00,1.0,1.0,1.0,101348.88,1.0
1,2,15647311.0,608.0,Spain,Female,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58,0.0
2,3,15619304.0,502.0,France,Female,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57,1.0
3,4,15701354.0,699.0,France,Female,39.0,1.0,0.00,2.0,0.0,0.0,93826.63,0.0
4,5,15737888.0,850.0,Spain,Female,43.0,5.0,125510.82,1.0,1.0,1.0,79084.10,0.0

In [17]:
a=a.drop(columns='RowNumber')

In [18]:
a.shape

(10000, 12)

In [19]:
a=a.drop(columns='CustomerId')

In [20]:
a.shape

(10000, 11)

In [21]:
# one hot encoding

In [22]:
a_encoded=pd.get_dummies(a,dtype='int',drop_first=True)

In [23]:
a_encoded

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619.0,37.0,2.0,0.00,1.0,1.0,1.0,101348.88,1.0,0,0,0
1,608.0,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58,0.0,0,1,0
2,502.0,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57,1.0,0,0,0
3,699.0,39.0,1.0,0.00,2.0,0.0,0.0,93826.63,0.0,0,0,0
4,850.0,43.0,5.0,125510.82,1.0,1.0,1.0,79084.10,0.0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771.0,39.0,5.0,0.00,2.0,1.0,0.0,96270.64,0.0,0,0,1
9996,516.0,35.0,10.0,57369.61,1.0,1.0,1.0,101699.77,0.0,0,0,1
9997,709.0,36.0,7.0,0.00,1.0,0.0,1.0,42085.58,1.0,0,0,0
9998,772.0,42.0,3.0,75075.31,2.0,1.0,0.0,92888.52,1.0,1,0,1
9999,792.0,28.0,5.0,130142.79,1.0,1.0,0.0,38190.78,0.0,0,0,0

In [24]:
# train test data split

In [25]:
X=a_encoded.drop(columns=['Exited'])
y=a_encoded['Exited']

In [26]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619.0,37.0,2.0,0.00,1.0,1.0,1.0,101348.88,0,0,0
1,608.0,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58,0,1,0
2,502.0,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57,0,0,0
3,699.0,39.0,1.0,0.00,2.0,0.0,0.0,93826.63,0,0,0
4,850.0,43.0,5.0,125510.82,1.0,1.0,1.0,79084.10,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771.0,39.0,5.0,0.00,2.0,1.0,0.0,96270.64,0,0,1
9996,516.0,35.0,10.0,57369.61,1.0,1.0,1.0,101699.77,0,0,1
9997,709.0,36.0,7.0,0.00,1.0,0.0,1.0,42085.58,0,0,0
9998,772.0,42.0,3.0,75075.31,2.0,1.0,0.0,92888.52,1,0,1
9999,792.0,28.0,5.0,130142.79,1.0,1.0,0.0,38190.78,0,0,0

In [27]:
y

0       1.0
1       0.0
2       1.0
3       0.0
4       0.0
       ...
9995    0.0
9996    0.0
9997    1.0
9998    1.0
9999    0.0
Name: Exited, Length: 10000, dtype: float64

In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
ss=StandardScaler()

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=12)

In [32]:
X_test.shape

(2000, 11)

In [33]:
## feature scalling

In [34]:
ap1=ss.fit_transform(X_train)

In [35]:
ap1

array([[ 0.74505051,  0.2130277 ,  0.7024164 , ..., -0.55809982,
        -0.55424682,  0.87410373],
       [ 0.95671785, -0.27624125, -0.72299579, ..., -0.55809982,
        -0.55424682, -1.14402898],
       [-0.74720423,  1.0937118 , -1.79205492, ..., -0.55809982,
        -0.55424682,  0.87410373],
       ...,
       [-1.30812268, -0.66765641,  0.7024164 , ..., -0.55809982,
        -0.55424682, -1.14402898],
       [-1.33987278,  0.50658907,  1.77147554, ..., -0.55809982,
        -0.55424682,  0.87410373],
       [ 0.82971745, -1.25477914, -0.36664274, ...,  1.79179416,
        -0.55424682,  0.87410373]], shape=(8000, 11))

In [36]:
len(ap1)

8000

In [37]:
ap2=ss.transform(X_test)

In [38]:
ap2

array([[-0.02753527, -0.17838746,  0.7024164 , ...,  1.79179416,
        -0.55424682,  0.87410373],
       [ 0.4275495 , -0.17838746,  1.41512249, ..., -0.55809982,
        -0.55424682,  0.87410373],
       [ 2.11030485, -0.17838746,  1.05876944, ..., -0.55809982,
        -0.55424682, -1.14402898],
       ...,
       [ 0.58630001, -0.17838746,  0.7024164 , ..., -0.55809982,
         1.8042503 , -1.14402898],
       [-0.34503628,  0.11517391, -1.79205492, ...,  1.79179416,
        -0.55424682, -1.14402898],
       [-1.42453971, -0.56980262,  1.77147554, ...,  1.79179416,
        -0.55424682, -1.14402898]], shape=(2000, 11))

In [39]:
X_Train_scale=pd.DataFrame(ap1,columns=X_train.columns)

In [40]:
X_Test_scale=pd.DataFrame(ap2,columns=X_test.columns)

In [41]:
X_Train_scale.shape

(8000, 11)

In [42]:
X_Test_scale.shape

(2000, 11)

In [ ]:
import tensorflow

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
from tensorflow  import keras

In [ ]:
model=Sequential()

In [ ]:
model.add(Dense(3, activation='sigmoid', input_shape=(11,)))

C:\Users\Shukant\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 3)                   │              36 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(loss='binary_crossentropy' , optimizer='adam',metrics=['accuracy'])          # adam (calculate the weight)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [ ]:
model.fit(X_Train_scale,y_train, epochs=20)        ## model is now trained

Epoch 1/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6104 - loss: 0.6648
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8086 - loss: 0.5318
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8096 - loss: 0.4742
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8096 - loss: 0.4492
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8098 - loss: 0.4365
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8105 - loss: 0.4290
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8112 - loss: 0.4240
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8139 - loss: 0.4205
Epoch 9/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8161 - loss: 0.4178
Epoch 10/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8170 - loss: 0.4156
Epoch 11/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8191 - loss: 0.4137
Epoch 12/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8213 - loss: 0.4118
Epoch 13/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8210 - loss: 0.4101
Epoch 14/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8209 - loss: 0.4084
Epoch 15/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8216 - loss: 0.4069
Epoch 16/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8207 - loss: 0.4052
Epoch 17/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8219 - loss: 0.4038
Epoch 18/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8229 - loss: 0.4024
Epoch 19/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8239 - loss: 0.4011
Epoch 20/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8244 - loss: 0.3999

In [ ]:
## model predict

In [ ]:
y1=model.predict(X_Test_scale)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [ ]:
ap2.evaluate(X_test, y_test)

AttributeError: 'numpy.ndarray' object has no attribute 'evaluate'